// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_cech_R2
List calc_cech_R2(float rmax, NumericMatrix xs, int nrow, int ncol, int K);
RcppExport SEXP _hyperlatent_calc_cech_R2(SEXP rmaxSEXP, SEXP xsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_cech_R2(rmax, xs, nrow, ncol, K));
    return rcpp_result_gen;
END_RCPP
}
// calc_cech_R3
List calc_cech_R3(float rmax, NumericMatrix xs, int nrow, int ncol, int K);
RcppExport SEXP _hyperlatent_calc_cech_R3(SEXP rmaxSEXP, SEXP xsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_cech_R3(rmax, xs, nrow, ncol, K));
    return rcpp_result_gen;
END_RCPP
}
// miniball_rsqr
double miniball_rsqr(NumericMatrix xmat, int d, int n);
RcppExport SEXP _hyperlatent_miniball_rsqr(SEXP xmatSEXP, SEXP dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(miniball_rsqr(xmat, d, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hyperlatent_calc_cech_R2", (DL_FUNC) &_hyperlatent_calc_cech_R2, 5},
    {"_hyperlatent_calc_cech_R3", (DL_FUNC) &_hyperlatent_calc_cech_R3, 5},
    {"_hyperlatent_miniball_rsqr", (DL_FUNC) &_hyperlatent_miniball_rsqr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hyperlatent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
